apiVersion: v1
kind: Pod 
metadata:
  name: redis-pod
  namespace: gerald-env
spec:
  containers:
  - image: redis
    name: redis 
    volumeMounts:
    - name: redis-storage
      mountPath: /data/redis 
  volumes:
    - name: redis-storage
      emptyDir: {}